// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApn-YxQKGRSYbtZ5XvkkHA43s5olwuApo',
    appId: '1:361510114529:web:503b17da180c062e87d3a0',
    messagingSenderId: '361510114529',
    projectId: 'origin-2e349',
    authDomain: 'origin-2e349.firebaseapp.com',
    databaseURL: 'https://origin-2e349-default-rtdb.firebaseio.com',
    storageBucket: 'origin-2e349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrDsapcwOfTNrdRw8-Oq4pfpgwn2HboI',
    appId: '1:361510114529:android:02f837ffb01d8c0487d3a0',
    messagingSenderId: '361510114529',
    projectId: 'origin-2e349',
    databaseURL: 'https://origin-2e349-default-rtdb.firebaseio.com',
    storageBucket: 'origin-2e349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvCO_2b7zrMp4ah1lJjjcuGEVEGSx0VU',
    appId: '1:361510114529:ios:cbee9bcd959a2a9e87d3a0',
    messagingSenderId: '361510114529',
    projectId: 'origin-2e349',
    databaseURL: 'https://origin-2e349-default-rtdb.firebaseio.com',
    storageBucket: 'origin-2e349.appspot.com',
    androidClientId: '361510114529-6837p745qeqkgcst5pmc3ckjvi3oj6i6.apps.googleusercontent.com',
    iosClientId: '361510114529-p4v1gqhe7pka0k0no6mo1m1fe9hde1f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.origin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcvCO_2b7zrMp4ah1lJjjcuGEVEGSx0VU',
    appId: '1:361510114529:ios:cbee9bcd959a2a9e87d3a0',
    messagingSenderId: '361510114529',
    projectId: 'origin-2e349',
    databaseURL: 'https://origin-2e349-default-rtdb.firebaseio.com',
    storageBucket: 'origin-2e349.appspot.com',
    androidClientId: '361510114529-6837p745qeqkgcst5pmc3ckjvi3oj6i6.apps.googleusercontent.com',
    iosClientId: '361510114529-p4v1gqhe7pka0k0no6mo1m1fe9hde1f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.origin',
  );
}
